name: Main CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  split-upm:
    name: split upm branch
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Split core upm branch
        run: |
          git push origin --delete core_upm &> /dev/null || echo core_upm branch not found
          git subtree split -P "$CORE_PKG_ROOT" -b core_upm
          git push -u origin core_upm
        env:
          CORE_PKG_ROOT: Assets/Package/com.didabu.core

      - name: Split appsflyer upm branch
        run: |
          git push origin --delete appsflyer_upm &> /dev/null || echo appsflyer_upm_dev branch not found
          git subtree split -P "$APPSFLYER_PKG_ROOT" -b appsflyer_upm
          git push -u origin appsflyer_upm
        env:
          APPSFLYER_PKG_ROOT: Assets/Package/com.didabu.appsflyer
